# Generated by Django 4.0.1 on 2022-10-17 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalCategory',
            new_name='Category',
        ),
    ]
