# Generated by Django 4.0.1 on 2022-10-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
    ]
