# Generated by Django 4.0.1 on 2022-10-30 07:35

from django.db import migrations, transaction
from django.utils import timezone

def create_objects(apps, schema_editor):
    # Для загрузки кода моделей используется специальный метод apps.get_model
    # Он позволяет загрузить ровно то состояние модели, которое было на момент применения этой миграции
    # Импортировать настоящие классы – плохая практика
    # так как в будущем вы можете удалить/переименовать эти модели, и тогда у вас будут ошибки импорта

    User = apps.get_model("core", "User")
    Board = apps.get_model("goals", "Board")
    BoardParticipant = apps.get_model("goals", "BoardParticipant")
    Category = apps.get_model("goals", "Category")

    current_time = timezone.now()

    with transaction.atomic():  # Применяем все изменения одной транзакцией
        for user in User.objects.all():  # Для каждого пользователя
            new_board = Board.objects.create(
                title="Мои цели",
                created=current_time,  # Проставляем вручную по той же причине, что описана вверху
                updated=current_time
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,  # Владелец, проставляем числом, не импортируем код по той же причине
                created=current_time,
                updated=current_time
            )

            # проставляем всем категориям пользователя его доску
            Category.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
