# Generated by Django 4.0.1 on 2022-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_category_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Дата выполнения'),
        ),
    ]
