# Generated by Django 4.0.1 on 2022-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.IntegerField(default=12345, max_length=5, verbose_name='Код для верификации'),
            preserve_default=False,
        ),
    ]
